### PR TITLE
Help page

### PR DESCRIPTION
**Pull request by MGLeyda**

### CODE REVIEW

**Review by edeguzman23 — CHANGES_REQUESTED** [review]
fix merge conflicts and we should be good!

**Review by MGLeyda — COMMENTED** [review]
Fixed issues

**Review by edeguzman23 — APPROVED** [review]
conflicts resolved! looks good!

**Review by JohnMcAtee — APPROVED** [review]

**Comment by elizabethrlemar** [comment]
already merged

**Pull request closed without merging**
